### ISSUE TITLE
This program is adapted from the pywireframe package. If the code is inappropriate, it is the problem of me or the pywireframe package. Please understand!

### ISSUE THREAD

**Issue by qfcy** [qfcy/PyWireframe#1]
本程序改编自PyWireframe包, 若有代码不妥当之处, 可能为原PyWireFrame包的问题, 也可能是我的问题, 敬请谅解!
This program is adapted from the pywireframe package. If the code is inappropriate, it is the problem of the original pywireframe package or the problem of me. Please understand!
如果新增/修改的代码有问题/bug, 联系作者: blog.csdn.net/qfcy_
If the new code has bugs, contact the author: blog.csdn.net/qfcy_

**Comment by qfcy** [comment]
PyWireframe包不是面向对象编程, 而且使用了较多的全局变量, 不习惯~ 
The pywireframe package is not object-oriented programming, and uses more global variables. It's not used to ~

**Comment by jbritain** [comment]
I cannot believe you would ever blame me for inappropriate code

**Comment by jbritain** [comment]
(I am the original developer of PyWireframe)

**Comment by qfcy** [comment]
> (I am the original developer of PyWireframe)

Oh, I'm sorry, I have changed my issue content.

**Comment by jbritain** [comment]
Ah, I was half joking. I'm not sure how well that comes across in translation.

It's very interesting to see what you've done with pywireframe!

I created it several years ago and it was my first proper Python project. I would never have expected anyone to think it was worth improving on
